sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:kojoley/boost
    - sudo apt-get update
    - lsb_release -a

install:
    - sudo apt-get install libboost1.58-dev
    - sudo apt-get install libboost-thread1.58-dev
    - sudo apt-get install libboost-coroutine1.58-dev
    - sudo apt-get install libboost-context1.58-dev
    - sudo apt-get install libboost-system1.58-dev
    - sudo apt-get install libboost-date_time1.58-dev
    - sudo apt-get install libboost-chrono1.58-dev
    - sudo apt-get install libboost-regex1.58-dev
    - sudo apt-get install cmake 

script: 
    - mkdir build; pushd build;
    - cmake .. && make -j4 && sudo make install && make test_small && make samples && make run_test
    - sudo rm * -rf && cmake .. -DENABLE_BOOST_COROUTINE=ON && make -j4 && sudo make install && make test_small && make samples && make run_test
    - sudo rm * -rf && cmake .. -DENABLE_SHARED_STACK=ON && make -j4 && sudo make install && make test_small && make samples && make run_test
    - popd;

after_success:
    - 

branches:
    only:
    - dev
    - master

notifications:
  email: true


