sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:andykimpe/cmake
    - sudo add-apt-repository -y ppa:kojoley/boost
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update || echo 'warning'
    - sudo apt-cache search boost | grep boost -i
    - lsb_release -a

install:
    - sudo apt-get install libboost1.58-dev
    - sudo apt-get install cmake 
    - .travis_scripts/gcc.sh

script: 
    - mkdir build; pushd build;
    - cmake .. && make -j4 && sudo make install && make test_small && make samples && make run_test
    - sudo rm * -rf && cmake .. -DENABLE_BOOST_COROUTINE=ON && make -j4 && sudo make install && make test_small && make samples && make run_test
    - sudo rm * -rf && cmake .. -DENABLE_SHARED_STACK=ON && make -j4 && sudo make install && make test_small && make samples && make run_test
    - popd;

after_success:
    - 

branches:
    only:
    - dev
    - master

notifications:
  email: true


